apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinghy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinghy-agent
  template:
    metadata:
      labels:
        app: dinghy-agent
    spec:
      containers:
        - name: main-app
          image: dinghy-agent
          imagePullPolicy: Never
          env:
            - name: BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BIND_PORT
              value: "7777"
            - name: ADVERTISE_ADDR
              value: dinghy-agent-svc.default.svc.cluster.local
            - name: ADVERTISE_PORT
              value: "7777"
            - name: CLUSTER_ADDR
              value: dinghy-agent-svc.default.svc.cluster.local
            - name: CLUSTER_PORT
              value: "7777"
            - name: NAME
              value: dinghy-agent
            - name:  GRPC_PORT
              value: "5001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - name: grpc
            containerPort: 5001
          - name: serf
            containerPort: 7777
